version: "3.4"

services:
  nglancerstatic-prod:
    build:
      context: ./nglancerstatic_prod
      dockerfile: nglancerstatic_prod.Dockerfile
    ports:
      - '8082:8080'

networks:
  default:
    external:
      name: lightserv-prod