version: "3.4"

services:
  worker:
    env_file: ../.dockerenv
    image: flaskcelery:prod
    command: ["celery",
              "worker",
              "-A",
              "celery_worker.cel",
              "--loglevel=info"]
    volumes:
      - ..:/app
      - ../lib:/opt/libraries
      - /jukebox/LightSheetData:/jukebox/LightSheetData
      - /jukebox/LightSheetTransfer:/jukebox/LightSheetTransfer
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  scheduler:
    env_file: ../.dockerenv
    image: flaskcelery:prod
    command: ["celery",
              "beat",
              "-A",
              "celery_worker.cel",
              "--schedule=/tmp/celerybeat-schedule",
              "--loglevel=info",
              "--pidfile=/tmp/celerybeat.pid"]
    volumes:
      - ..:/app
      - ../lib:/opt/libraries
    depends_on:
      - worker
    restart: unless-stopped
networks:
  default:
    external:
      name: lightserv-prod