version: "3.4"

services:
  confproxy:
    env_file: ../.dockerenv
    image: jupyterhub/configurable-http-proxy:3.1.1
    # expose the proxy to the world
    ports:
      - "8004:8000"
      - "8005:8001"
    command: ['configurable-http-proxy',
              '--auto-rewrite',
              '--no-include-prefix',
              '--no-prepend-path',
              '--log-level', 'debug',
              '--api-ip', '0.0.0.0']
  testflask:
    env_file: ../.testdockerenv
    hostname: docker_lightserv
    image: flaskcelery:latest
    command: "pytest -p no:cacheprovider -vs lightserv/tests/test_imaging.py"
    volumes:
      - ..:/app # so changes made to the app are propagated to the container without having to rebuild
      - /jukebox/LightSheetData:/jukebox/LightSheetData
      - /jukebox/LightSheetTransfer:/jukebox/LightSheetTransfer
      - ../lib:/opt/libraries # for progproxy api
    ports:
      - '5010:5000'
  coverage:
    env_file: ../.testdockerenv
    hostname: docker_lightserv
    image: flaskcelery:test
    command: "pytest -p no:cacheprovider --cov=lightserv/main --cov-report=html -vs lightserv/tests/test_main.py::test_FAQ"
    volumes:
      - ..:/app # so changes made to the app are propagated to the container without having to rebuild
      - /jukebox/LightSheetData:/jukebox/LightSheetData
      - /jukebox/LightSheetTransfer:/jukebox/LightSheetTransfer
      - ../lib:/opt/libraries # for progproxy api
    ports:
      - '5010:5000'
  viewer-launcher:
    env_file: ../.testdockerenv
    image: viewer-launcher:test
    command: ["python", "run.py"]
    volumes:
      - ../viewer-launcher:/app
      - /jukebox/LightSheetData:/jukebox/LightSheetData
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '5006:5005'
networks:
  default:
    external:
      name: lightserv-test