from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectField, BooleanField
from wtforms.fields.html5 import DateField, DateTimeLocalField
from wtforms.validators import DataRequired, Length, InputRequired, ValidationError

datetimeformat='%Y-%m-%dT%H:%M' # To get form.field.data to work. Does not work with the default (bug)


class iDiscoPlusImmunoForm(FlaskForm):
	""" The form for entering clearing information """
	perfusion_date = DateField('Day 1: Perfusion')
	perfusion_date_submit = SubmitField('Update')
	
	dehydr_date = DateField('Day 2: Dehydration')
	dehydr_date_submit = SubmitField('Push date to calendar')
	time_dehydr_pbs_wash1 = DateTimeLocalField('1xPBS 30 min R@RT',format=datetimeformat)
	time_dehydr_pbs_wash1_submit = SubmitField('Update')
	time_dehydr_pbs_wash2 = DateTimeLocalField('2xPBS 30 min R@RT',format=datetimeformat)
	time_dehydr_pbs_wash2_submit = SubmitField('Update')
	time_dehydr_pbs_wash3 = DateTimeLocalField('3xPBS 30 min R@RT',format=datetimeformat)
	time_dehydr_pbs_wash3_submit = SubmitField('Update')
	time_dehydr_ch3oh_20percent_wash1 = DateTimeLocalField('20% CH3OH R@RTx1hr',format=datetimeformat)
	time_dehydr_ch3oh_20percent_wash1_submit = SubmitField('Update')
	time_dehydr_ch3oh_40percent_wash1 = DateTimeLocalField('40% CH3OH R@RTx1hr',format=datetimeformat)
	time_dehydr_ch3oh_40percent_wash1_submit = SubmitField('Update')
	time_dehydr_ch3oh_60percent_wash1 = DateTimeLocalField('60% CH3OH R@RTx1hr',format=datetimeformat)
	time_dehydr_ch3oh_60percent_wash1_submit = SubmitField('Update')
	time_dehydr_ch3oh_80percent_wash1 = DateTimeLocalField('80% CH3OH R@RTx1hr',format=datetimeformat)
	time_dehydr_ch3oh_80percent_wash1_submit = SubmitField('Update')
	time_dehydr_ch3oh_100percent_wash1 = DateTimeLocalField('100% CH3OH R@RTx1hr (first hour)',format=datetimeformat)
	time_dehydr_ch3oh_100percent_wash1_submit = SubmitField('Update')
	time_dehydr_ch3oh_100percent_wash2 = DateTimeLocalField('100% CH3OH R@RTx1hr (second hour)',format=datetimeformat)
	time_dehydr_ch3oh_100percent_wash2_submit = SubmitField('Update')
	time_dehydr_h202_wash1 = DateTimeLocalField('5% H2O2(30%) in CH3OH(100%) O/N R@RT (1 part H2O2:5 parts methanol)',format=datetimeformat)
	time_dehydr_h202_wash1_submit = SubmitField('Update')

	rehydr_date = DateField('Day 3: Rehydration')
	rehydr_date_submit = SubmitField('Push date to calendar')
	time_rehydr_ch3oh_100percent_wash1 = DateTimeLocalField('100% CH3OH R@RTx1hr',format=datetimeformat)
	time_rehydr_ch3oh_100percent_wash1_submit = SubmitField('Update')
	time_rehydr_ch3oh_80percent_wash1 = DateTimeLocalField('80% CH3OH R@RTx1hr',format=datetimeformat)
	time_rehydr_ch3oh_80percent_wash1_submit = SubmitField('Update')
	time_rehydr_ch3oh_60percent_wash1 = DateTimeLocalField('60% CH3OH R@RTx1hr',format=datetimeformat)
	time_rehydr_ch3oh_60percent_wash1_submit = SubmitField('Update')
	time_rehydr_ch3oh_40percent_wash1 = DateTimeLocalField('40% CH3OH R@RTx1hr',format=datetimeformat)
	time_rehydr_ch3oh_40percent_wash1_submit = SubmitField('Update')
	time_rehydr_ch3oh_20percent_wash1 = DateTimeLocalField('20% CH3OH R@RTx1hr',format=datetimeformat)
	time_rehydr_ch3oh_20percent_wash1_submit = SubmitField('Update')
	time_rehydr_pbs_wash1 = DateTimeLocalField('PBS R@RTx1hr',format=datetimeformat)
	time_rehydr_pbs_wash1_submit = SubmitField('Update')
	time_rehydr_sodium_azide_wash1 = DateTimeLocalField('0.2%TritonX-100/1xPBS/0.1% sodium azide R@RTx1hr (first hour)',format=datetimeformat)
	time_rehydr_sodium_azide_wash1_submit = SubmitField('Update')
	time_rehydr_sodium_azide_wash2 = DateTimeLocalField('0.2%TritonX-100/1xPBS/0.1% sodium azide R@RTx1hr (second hour)',format=datetimeformat)
	time_rehydr_sodium_azide_wash2_submit = SubmitField('Update')
	time_rehydr_glycine_wash1 = DateTimeLocalField('20%DMSO/0.3M glycine/0.2% TritonX-100/0.1%sodium azide/1xPBS R@37C for 2 days',format=datetimeformat)
	time_rehydr_glycine_wash1_submit = SubmitField('Update')

	blocking_date = DateField('Day 4: Blocking')
	blocking_date_submit = SubmitField('Push date to calendar')
	time_blocking_start_roomtemp = DateTimeLocalField('Sample R@RT for ~1.5hrs',format=datetimeformat)
	time_blocking_start_roomtemp_submit = SubmitField('Update')
	time_blocking_donkey_serum = DateTimeLocalField('10% DMSO / 6% Donkey seum / 0.2%TritonX-100 / 0.1%sodium azide / 1xPBS, R@37°C for 2-3 days',format=datetimeformat)
	time_blocking_donkey_serum_submit = SubmitField('Update')

	antibody1_date = DateField('Day 5: Primary Antibody')
	antibody1_date_submit = SubmitField('Push date to calendar')
	time_antibody1_start_roomtemp = DateTimeLocalField('Sample R@RT for ~1.5hrs',format=datetimeformat)
	time_antibody1_start_roomtemp_submit = SubmitField('Update')
	time_antibody1_ptwh_wash1 = DateTimeLocalField('PTwH R@RTx1hr (first hour)',format=datetimeformat)
	time_antibody1_ptwh_wash1_submit = SubmitField('Update')
	time_antibody1_ptwh_wash2 = DateTimeLocalField('PTwH R@RTx1hr (second hour)',format=datetimeformat)
	time_antibody1_ptwh_wash2_submit = SubmitField('Update')
	time_antibody1_added = DateTimeLocalField('primary antibody (5% DMSO, 3% donkey serum in PTwH); 37C 7d',format=datetimeformat)
	time_antibody1_added_submit = SubmitField('Update')

	wash1_date = DateField('Day 6: Wash')
	wash1_date_submit = SubmitField('Push date to calendar')
	time_wash1_start_roomtemp = DateTimeLocalField('Sample R@RT for ~1.5hrs',format=datetimeformat)
	time_wash1_start_roomtemp_submit = SubmitField('Update')
	time_wash1_ptwh_wash1 = DateTimeLocalField('PTwH 10 min',format=datetimeformat)
	time_wash1_ptwh_wash1_submit = SubmitField('Update')
	time_wash1_ptwh_wash2 = DateTimeLocalField('PTwH 15 min',format=datetimeformat)
	time_wash1_ptwh_wash2_submit = SubmitField('Update')
	time_wash1_ptwh_wash3 = DateTimeLocalField('PTwH 30 min',format=datetimeformat)
	time_wash1_ptwh_wash3_submit = SubmitField('Update')
	time_wash1_ptwh_wash4 = DateTimeLocalField('PTwH 1 hr',format=datetimeformat)
	time_wash1_ptwh_wash4_submit = SubmitField('Update')
	time_wash1_ptwh_wash5 = DateTimeLocalField('PTwH 2 hr',format=datetimeformat)
	time_wash1_ptwh_wash5_submit = SubmitField('Update')

	antibody2_date = DateField('Day 7: Secondary Antibody')
	antibody2_date_submit = SubmitField('Push date to calendar')
	time_antibody2_added = DateTimeLocalField('2nd antibody solution R@37°C for 7 days (3% donkey serum/PTwH)',format=datetimeformat)
	time_antibody2_added_submit = SubmitField('Update')

	wash2_date = DateField('Day 8: Wash')
	wash2_date_submit = SubmitField('Push date to calendar')
	time_wash2_start_roomtemp = DateTimeLocalField('Sample R@RT for ~1.5hrs',format=datetimeformat)
	time_wash2_start_roomtemp_submit = SubmitField('Update')
	time_wash2_ptwh_wash1 = DateTimeLocalField('PTwH 10 min',format=datetimeformat)
	time_wash2_ptwh_wash1_submit = SubmitField('Update')
	time_wash2_ptwh_wash2 = DateTimeLocalField('PTwH 15 min',format=datetimeformat)
	time_wash2_ptwh_wash2_submit = SubmitField('Update')
	time_wash2_ptwh_wash3 = DateTimeLocalField('PTwH 30 min',format=datetimeformat)
	time_wash2_ptwh_wash3_submit = SubmitField('Update')
	time_wash2_ptwh_wash4 = DateTimeLocalField('PTwH 1 hr',format=datetimeformat)
	time_wash2_ptwh_wash4_submit = SubmitField('Update')
	time_wash2_ptwh_wash5 = DateTimeLocalField('PTwH 2 hr',format=datetimeformat)
	time_wash2_ptwh_wash5_submit = SubmitField('Update')

	clearing_date = DateField('Day 9: Clearing')
	clearing_date_submit = SubmitField('Push date to calendar')
	time_clearing_ch3oh_20percent_wash1 = DateTimeLocalField('20% CH3OH R@RTx1hr',format=datetimeformat)
	time_clearing_ch3oh_20percent_wash1_submit = SubmitField('Update')
	time_clearing_ch3oh_40percent_wash1 = DateTimeLocalField('40% CH3OH R@RTx1hr',format=datetimeformat)
	time_clearing_ch3oh_40percent_wash1_submit = SubmitField('Update')
	time_clearing_ch3oh_60percent_wash1 = DateTimeLocalField('60% CH3OH R@RTx1hr',format=datetimeformat)
	time_clearing_ch3oh_60percent_wash1_submit = SubmitField('Update')
	time_clearing_ch3oh_80percent_wash1 = DateTimeLocalField('80% CH3OH R@RTx1hr',format=datetimeformat)
	time_clearing_ch3oh_80percent_wash1_submit = SubmitField('Update')
	time_clearing_ch3oh_100percent_wash1 = DateTimeLocalField('100% CH3OH R@RTx1hr (hour 1)',format=datetimeformat)
	time_clearing_ch3oh_100percent_wash1_submit = SubmitField('Update')
	time_clearing_ch3oh_100percent_wash2 = DateTimeLocalField('100% CH3OH R@RTx1hr (hour 2)',format=datetimeformat)
	time_clearing_ch3oh_100percent_wash2_submit = SubmitField('Update')
	time_clearing_dcm_66percent_ch3oh_33percent = DateTimeLocalField('66% DCM / 33% CH3OH R@RTx3hrs',format=datetimeformat)
	time_clearing_dcm_66percent_ch3oh_33percent_submit = SubmitField('Update')
	time_clearing_dcm_wash1 = DateTimeLocalField('100% DCM R@RTx15 min (wash 1)',format=datetimeformat)
	time_clearing_dcm_wash1_submit = SubmitField('Update')
	time_clearing_dcm_wash2 = DateTimeLocalField('100% DCM R@RTx15 min (wash 2)',format=datetimeformat)
	time_clearing_dcm_wash2_submit = SubmitField('Update')
	time_clearing_dbe = DateTimeLocalField('100% DBE > hr',format=datetimeformat)
	time_clearing_dbe_submit = SubmitField('Update')
	time_clearing_new_tubes = DateTimeLocalField('put brains in new tubes with prepoured 100% DBE no rocking',format=datetimeformat)
	time_clearing_new_tubes_submit = SubmitField('Update')
	clearing_notes = TextAreaField('Clearing Notes')
	clearing_notes_submit = SubmitField('Update')

	submit = SubmitField('Done')

class iDiscoAbbreviatedForm(FlaskForm):
	""" The form for entering clearing information """
	perfusion_date = DateField('Day 1: Perfusion')
	perfusion_date_submit = SubmitField('Update')
	
	pbs_date = DateField('Day 2: PBS wash')
	pbs_date_submit = SubmitField('Push date to calendar')
	time_pbs_wash1 = DateTimeLocalField('Wash 1',format=datetimeformat)
	time_pbs_wash1_submit = SubmitField('Update')
	time_pbs_wash2 = DateTimeLocalField('Wash 2',format=datetimeformat)
	time_pbs_wash2_submit = SubmitField('Update')
	time_pbs_wash3 = DateTimeLocalField('Wash 3',format=datetimeformat)
	time_pbs_wash3_submit = SubmitField('Update')
	
	dehydr_date = DateField('Day 2 or 3: Dehydration')
	dehydr_date_submit = SubmitField('Push date to calendar')
	time_dehydr_ch3oh_20percent_wash1 = DateTimeLocalField('20% CH3OH R@RTx1hr',format=datetimeformat)
	time_dehydr_ch3oh_20percent_wash1_submit = SubmitField('Update')
	time_dehydr_ch3oh_40percent_wash1 = DateTimeLocalField('40% CH3OH R@RTx1hr',format=datetimeformat)
	time_dehydr_ch3oh_40percent_wash1_submit = SubmitField('Update')
	time_dehydr_ch3oh_60percent_wash1 = DateTimeLocalField('60% CH3OH R@RTx1hr',format=datetimeformat)
	time_dehydr_ch3oh_60percent_wash1_submit = SubmitField('Update')
	time_dehydr_ch3oh_80percent_wash1 = DateTimeLocalField('80% CH3OH R@RTx1hr',format=datetimeformat)
	time_dehydr_ch3oh_80percent_wash1_submit = SubmitField('Update')
	time_dehydr_ch3oh_100percent_wash1 = DateTimeLocalField('100% CH3OH R@RTx1hr (first hour)',format=datetimeformat)
	time_dehydr_ch3oh_100percent_wash1_submit = SubmitField('Update')
	time_dehydr_ch3oh_100percent_wash2 = DateTimeLocalField('100% CH3OH R@RTx1hr (second hour)',format=datetimeformat)
	time_dehydr_ch3oh_100percent_wash2_submit = SubmitField('Update')
	time_dehydr_dcm_66percent_ch3oh_33percent = DateTimeLocalField('66% DCM / 33% CH3OH R@RTx3hrs',format=datetimeformat)
	time_dehydr_dcm_66percent_ch3oh_33percent_submit = SubmitField('Update')
	time_dehydr_dcm_wash1 = DateTimeLocalField('100% DCM R@RTx15 min (wash 1)',format=datetimeformat)
	time_dehydr_dcm_wash1_submit = SubmitField('Update')
	time_dehydr_dcm_wash2 = DateTimeLocalField('100% DCM R@RTx15 min (wash 2)',format=datetimeformat)
	time_dehydr_dcm_wash2_submit = SubmitField('Update')
	time_dehydr_dbe_wash1 = DateTimeLocalField('100% DBE > hr',format=datetimeformat)
	time_dehydr_dbe_wash1_submit = SubmitField('Update')
	time_dehydr_dbe_wash2 = DateTimeLocalField('100% DBE no rocking',format=datetimeformat)
	time_dehydr_dbe_wash2_submit = SubmitField('Update')

	clearing_notes = TextAreaField('Clearing Notes')
	clearing_notes_submit = SubmitField('Update')

	submit = SubmitField('Done')

class iDiscoAbbreviatedRatForm(FlaskForm):
	""" The form for entering clearing information """
	perfusion_date = DateField('Day 1: Perfusion')
	perfusion_date_submit = SubmitField('Update')
	
	pbs_date = DateField('Day 2: PBS wash')
	pbs_date_submit = SubmitField('Push date to calendar')
	time_pbs_wash1 = DateTimeLocalField('1xPBS R@RT30min',format=datetimeformat)
	time_pbs_wash1_submit = SubmitField('Update')
	time_pbs_wash2 = DateTimeLocalField('1xPBS R@RT30min',format=datetimeformat)
	time_pbs_wash2_submit = SubmitField('Update')
	time_pbs_wash3 = DateTimeLocalField('1xPBS R@RT30min',format=datetimeformat)
	time_pbs_wash3_submit = SubmitField('Update')
	
	dehydr_date = DateField('Day 2 or 3: Dehydration')
	dehydr_date_submit = SubmitField('Push date to calendar')
	time_dehydr_ch3oh_20percent_wash1 = DateTimeLocalField('20% CH3OH R@RTX3hrs',format=datetimeformat)
	time_dehydr_ch3oh_20percent_wash1_submit = SubmitField('Update')
	time_dehydr_ch3oh_40percent_wash1 = DateTimeLocalField('40% CH3OH R@RTX3hrs',format=datetimeformat)
	time_dehydr_ch3oh_40percent_wash1_submit = SubmitField('Update')
	time_dehydr_ch3oh_60percent_wash1 = DateTimeLocalField('60% CH3OH R@RTX3hrs',format=datetimeformat)
	time_dehydr_ch3oh_60percent_wash1_submit = SubmitField('Update')
	time_dehydr_ch3oh_80percent_wash1 = DateTimeLocalField('80% CH3OH R@RTX3hrs',format=datetimeformat)
	time_dehydr_ch3oh_80percent_wash1_submit = SubmitField('Update')
	time_dehydr_ch3oh_100percent_wash1 = DateTimeLocalField('100% CH3OH R@RTX3hrs',format=datetimeformat)
	time_dehydr_ch3oh_100percent_wash1_submit = SubmitField('Update')
	time_dehydr_ch3oh_100percent_wash2 = DateTimeLocalField('100% CH3OH R@RTX3hrs (or overnight)',format=datetimeformat)
	time_dehydr_ch3oh_100percent_wash2_submit = SubmitField('Update')
	time_dehydr_h202_wash1 = DateTimeLocalField('5% H202 / Methanol (1 part 30% H202: 5 parts 100% methanol) ',format=datetimeformat)
	time_dehydr_h202_wash1_submit = SubmitField('Update')
	time_dehydr_ch3oh_100percent_wash3 = DateTimeLocalField('100% CH3OH R@RTX2hrs',format=datetimeformat)
	time_dehydr_ch3oh_100percent_wash3_submit = SubmitField('Update')
	time_dehydr_ch3oh_100percent_wash4 = DateTimeLocalField('100% CH3OH R@RTX2hrs',format=datetimeformat)
	time_dehydr_ch3oh_100percent_wash4_submit = SubmitField('Update')
	time_dehydr_ch3oh_100percent_wash5 = DateTimeLocalField('100% CH3OH R@RTX2hrs (or overnight)',format=datetimeformat)
	time_dehydr_ch3oh_100percent_wash5_submit = SubmitField('Update')

	time_dehydr_dcm_66percent_ch3oh_33percent = DateTimeLocalField('66% DCM / 33% CH3OH R@RTx6hrs',format=datetimeformat)
	time_dehydr_dcm_66percent_ch3oh_33percent_submit = SubmitField('Update')
	time_dehydr_dcm_wash1 = DateTimeLocalField('100% DCM R@RTx1hr (wash 1)',format=datetimeformat)
	time_dehydr_dcm_wash1_submit = SubmitField('Update')
	time_dehydr_dcm_wash2 = DateTimeLocalField('100% DCM R@RTx1hr (wash 2)',format=datetimeformat)
	time_dehydr_dcm_wash2_submit = SubmitField('Update')
	time_dehydr_dbe_wash1 = DateTimeLocalField('100% DBE > 3 hrs',format=datetimeformat)
	time_dehydr_dbe_wash1_submit = SubmitField('Update')
	time_dehydr_dbe_wash2 = DateTimeLocalField('100% DBE no rocking',format=datetimeformat)
	time_dehydr_dbe_wash2_submit = SubmitField('Update')

	clearing_notes = TextAreaField('Clearing Notes')
	clearing_notes_submit = SubmitField('Update')

	submit = SubmitField('Done')

class uDiscoForm(FlaskForm):
	""" The form for requesting a new experiment/dataset """
	notes = TextAreaField('uDISCO Notes',validators=[Length(max=1000)])
	submit = SubmitField('Submit Changes')	

class iDiscoEduForm(FlaskForm):
	""" The form for requesting a new experiment/dataset """
	notes = TextAreaField('iDISCO_EdU Notes',validators=[Length(max=1000)])
	submit = SubmitField('Submit Changes')	