from flask_wtf import FlaskForm
from wtforms import SubmitField, TextAreaField
from wtforms.fields.html5 import DateField, DateTimeLocalField
from wtforms.validators import DataRequired, Length, InputRequired, ValidationError, Optional

datetimeformat='%Y-%m-%dT%H:%M' # To get form.field.data to work. Does not work with the default (bug)

def OptionalDateField(description='',validators=[]):
	""" A custom field that makes the DateField optional """
	validators.append(Optional())
	field = DateField(description,validators)
	return field

def OptionalDateTimeLocalField(description='',validators=[],format=datetimeformat):
	""" A custom field that makes the DateTimeLocalField optional
	and applies a specific formatting to fix a bug in the default formatting """
	validators.append(Optional())
	field = DateTimeLocalField(description,validators,format=format)
	return field

class iDiscoPlusImmunoForm(FlaskForm):
	""" The form for entering clearing information """
	title = 'iDISCO+ Immunostaining'
	exp_notes = TextAreaField('Experiment Notes: If anything unusual happened during the \
		experiment that might affect clearing, please note it here.',validators=[Length(max=500)])
	exp_notes_submit = SubmitField('Update')
	
	""" Dehydration """
	dehydr_date = OptionalDateField('Dehydration')
	dehydr_date_submit = SubmitField('Push date to calendar (optional)')
	time_dehydr_pbs_wash1 = OptionalDateTimeLocalField('1xPBS 30 min R@RT')
	time_dehydr_pbs_wash1_submit = SubmitField('Update')
	dehydr_pbs_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	dehydr_pbs_wash1_notes_submit = SubmitField('Update Notes')
	time_dehydr_pbs_wash2 = OptionalDateTimeLocalField('2xPBS 30 min R@RT')
	time_dehydr_pbs_wash2_submit = SubmitField('Update')
	dehydr_pbs_wash2_notes = TextAreaField('Notes',validators=[Length(max=250)])
	dehydr_pbs_wash2_notes_submit = SubmitField('Update Notes')
	time_dehydr_pbs_wash3 = OptionalDateTimeLocalField('3xPBS 30 min R@RT')
	time_dehydr_pbs_wash3_submit = SubmitField('Update')
	dehydr_pbs_wash3_notes = TextAreaField('Notes',validators=[Length(max=250)])
	dehydr_pbs_wash3_notes_submit = SubmitField('Update Notes')
	time_dehydr_methanol_20percent_wash1 = OptionalDateTimeLocalField('20% methanol R@RTx1hr')
	time_dehydr_methanol_20percent_wash1_submit = SubmitField('Update')
	dehydr_methanol_20percent_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	dehydr_methanol_20percent_wash1_notes_submit = SubmitField('Update Notes')
	time_dehydr_methanol_40percent_wash1 = OptionalDateTimeLocalField('40% methanol R@RTx1hr')
	time_dehydr_methanol_40percent_wash1_submit = SubmitField('Update')
	dehydr_methanol_40percent_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	dehydr_methanol_40percent_wash1_notes_submit = SubmitField('Update Notes')
	time_dehydr_methanol_60percent_wash1 = OptionalDateTimeLocalField('60% methanol R@RTx1hr')
	time_dehydr_methanol_60percent_wash1_submit = SubmitField('Update')
	dehydr_methanol_60percent_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	dehydr_methanol_60percent_wash1_notes_submit = SubmitField('Update Notes')
	time_dehydr_methanol_80percent_wash1 = OptionalDateTimeLocalField('80% methanol R@RTx1hr')
	time_dehydr_methanol_80percent_wash1_submit = SubmitField('Update')
	dehydr_methanol_80percent_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	dehydr_methanol_80percent_wash1_notes_submit = SubmitField('Update Notes')
	time_dehydr_methanol_100percent_wash1 = OptionalDateTimeLocalField('100% methanol R@RTx1hr (first hour)')
	time_dehydr_methanol_100percent_wash1_submit = SubmitField('Update')
	dehydr_methanol_100percent_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	dehydr_methanol_100percent_wash1_notes_submit = SubmitField('Update Notes')
	time_dehydr_methanol_100percent_wash2 = OptionalDateTimeLocalField('100% methanol R@RTx1hr (second hour)')
	time_dehydr_methanol_100percent_wash2_submit = SubmitField('Update')
	dehydr_methanol_100percent_wash2_notes = TextAreaField('Notes',validators=[Length(max=250)])
	dehydr_methanol_100percent_wash2_notes_submit = SubmitField('Update Notes')
	time_dehydr_peroxide_wash1 = OptionalDateTimeLocalField('5% peroxide (30%) in methanol(100%) O/N R@RT (1 part peroxide5 parts methanol)')
	time_dehydr_peroxide_wash1_submit = SubmitField('Update')
	dehydr_peroxide_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	dehydr_peroxide_wash1_notes_submit = SubmitField('Update Notes')

	""" Rehydration """
	rehydr_date = OptionalDateField('Rehydration')
	rehydr_date_submit = SubmitField('Push date to calendar (optional)')
	time_rehydr_methanol_100percent_wash1 = OptionalDateTimeLocalField('100% methanol R@RTx1hr')
	time_rehydr_methanol_100percent_wash1_submit = SubmitField('Update')
	rehydr_methanol_100percent_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	rehydr_methanol_100percent_wash1_notes_submit = SubmitField('Update Notes')
	time_rehydr_methanol_80percent_wash1 = OptionalDateTimeLocalField('80% methanol R@RTx1hr')
	time_rehydr_methanol_80percent_wash1_submit = SubmitField('Update')
	rehydr_methanol_80percent_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	rehydr_methanol_80percent_wash1_notes_submit = SubmitField('Update Notes')
	time_rehydr_methanol_60percent_wash1 = OptionalDateTimeLocalField('60% methanol R@RTx1hr')
	time_rehydr_methanol_60percent_wash1_submit = SubmitField('Update')
	rehydr_methanol_60percent_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	rehydr_methanol_60percent_wash1_notes_submit = SubmitField('Update Notes')
	time_rehydr_methanol_40percent_wash1 = OptionalDateTimeLocalField('40% methanol R@RTx1hr')
	time_rehydr_methanol_40percent_wash1_submit = SubmitField('Update')
	rehydr_methanol_40percent_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	rehydr_methanol_40percent_wash1_notes_submit = SubmitField('Update Notes')
	time_rehydr_methanol_20percent_wash1 = OptionalDateTimeLocalField('20% methanol R@RTx1hr')
	time_rehydr_methanol_20percent_wash1_submit = SubmitField('Update')
	rehydr_methanol_20percent_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	rehydr_methanol_20percent_wash1_notes_submit = SubmitField('Update Notes')
	time_rehydr_pbs_wash1 = OptionalDateTimeLocalField('PBS R@RTx1hr')
	time_rehydr_pbs_wash1_submit = SubmitField('Update')
	rehydr_pbs_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	rehydr_pbs_wash1_notes_submit = SubmitField('Update Notes')
	time_rehydr_sodium_azide_wash1 = OptionalDateTimeLocalField('0.2%TritonX-100/1xPBS/0.1% sodium azide R@RTx1hr (first hour)')
	time_rehydr_sodium_azide_wash1_submit = SubmitField('Update')
	rehydr_sodium_azide_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	rehydr_sodium_azide_wash1_notes_submit = SubmitField('Update Notes')
	time_rehydr_sodium_azide_wash2 = OptionalDateTimeLocalField('0.2%TritonX-100/1xPBS/0.1% sodium azide R@RTx1hr (second hour)')
	time_rehydr_sodium_azide_wash2_submit = SubmitField('Update')
	rehydr_sodium_azide_wash2_notes = TextAreaField('Notes',validators=[Length(max=250)])
	rehydr_sodium_azide_wash2_notes_submit = SubmitField('Update Notes')
	time_rehydr_glycine_wash1 = OptionalDateTimeLocalField('20%DMSO/0.3M glycine/0.2% TritonX-100/0.1%sodium azide/1xPBS R@37C for 2 days')
	time_rehydr_glycine_wash1_submit = SubmitField('Update')
	rehydr_glycine_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	rehydr_glycine_wash1_notes_submit = SubmitField('Update Notes')

	""" Blocking """
	blocking_date = OptionalDateField('Blocking')
	blocking_date_submit = SubmitField('Push date to calendar (optional)')
	time_blocking_start_roomtemp = OptionalDateTimeLocalField('Sample R@RT for ~1.5hrs')
	time_blocking_start_roomtemp_submit = SubmitField('Update')
	blocking_start_roomtemp_notes = TextAreaField('Notes',validators=[Length(max=250)])
	blocking_start_roomtemp_notes_submit = SubmitField('Update Notes')
	time_blocking_donkey_serum = OptionalDateTimeLocalField('10% DMSO / 6% Donkey seum / 0.2%TritonX-100 / 0.1%sodium azide / 1xPBS, R@37°C for 2-3 days')
	time_blocking_donkey_serum_submit = SubmitField('Update')
	blocking_donkey_serum_notes = TextAreaField('Notes',validators=[Length(max=250)])
	blocking_donkey_serum_notes_submit = SubmitField('Update Notes')

	""" Primary Antibody """
	antibody1_date = OptionalDateField('Primary Antibody')
	antibody1_date_submit = SubmitField('Push date to calendar (optional)')
	time_antibody1_start_roomtemp = OptionalDateTimeLocalField('Sample R@RT for ~1.5hrs')
	time_antibody1_start_roomtemp_submit = SubmitField('Update')
	antibody1_start_roomtemp_notes = TextAreaField('Notes',validators=[Length(max=250)])
	antibody1_start_roomtemp_notes_submit = SubmitField('Update Notes')
	time_antibody1_ptwh_wash1 = OptionalDateTimeLocalField('PTwH R@RTx1hr (first hour)')
	time_antibody1_ptwh_wash1_submit = SubmitField('Update')
	antibody1_ptwh_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	antibody1_ptwh_wash1_notes_submit = SubmitField('Update Notes')
	time_antibody1_ptwh_wash2 = OptionalDateTimeLocalField('PTwH R@RTx1hr (second hour)')
	time_antibody1_ptwh_wash2_submit = SubmitField('Update')
	antibody1_ptwh_wash2_notes = TextAreaField('Notes',validators=[Length(max=250)])
	antibody1_ptwh_wash2_notes_submit = SubmitField('Update Notes')
	time_antibody1_added = OptionalDateTimeLocalField('primary antibody (5% DMSO, 3% donkey serum in PTwH); 37C 7d')
	time_antibody1_added_submit = SubmitField('Update')
	antibody1_added_notes = TextAreaField('Notes',validators=[Length(max=250)])
	antibody1_added_notes_submit = SubmitField('Update Notes')

	""" Wash 1 """
	wash1_date = OptionalDateField('Wash')
	wash1_date_submit = SubmitField('Push date to calendar (optional)')
	time_wash1_start_roomtemp = OptionalDateTimeLocalField('Sample R@RT for ~1.5hrs')
	time_wash1_start_roomtemp_submit = SubmitField('Update')
	wash1_start_roomtemp_notes = TextAreaField('Notes',validators=[Length(max=250)])
	wash1_start_roomtemp_notes_submit = SubmitField('Update Notes')
	time_wash1_ptwh_wash1 = OptionalDateTimeLocalField('PTwH 10 min')
	time_wash1_ptwh_wash1_submit = SubmitField('Update')
	wash1_ptwh_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	wash1_ptwh_wash1_notes_submit = SubmitField('Update Notes')
	time_wash1_ptwh_wash2 = OptionalDateTimeLocalField('PTwH 15 min')
	time_wash1_ptwh_wash2_submit = SubmitField('Update')
	wash1_ptwh_wash2_notes = TextAreaField('Notes',validators=[Length(max=250)])
	wash1_ptwh_wash2_notes_submit = SubmitField('Update Notes')
	time_wash1_ptwh_wash3 = OptionalDateTimeLocalField('PTwH 30 min')
	time_wash1_ptwh_wash3_submit = SubmitField('Update')
	wash1_ptwh_wash3_notes = TextAreaField('Notes',validators=[Length(max=250)])
	wash1_ptwh_wash3_notes_submit = SubmitField('Update Notes')
	time_wash1_ptwh_wash4 = OptionalDateTimeLocalField('PTwH 1 hr')
	time_wash1_ptwh_wash4_submit = SubmitField('Update')
	wash1_ptwh_wash4_notes = TextAreaField('Notes',validators=[Length(max=250)])
	wash1_ptwh_wash4_notes_submit = SubmitField('Update Notes')
	time_wash1_ptwh_wash5 = OptionalDateTimeLocalField('PTwH 2 hr')
	time_wash1_ptwh_wash5_submit = SubmitField('Update')
	wash1_ptwh_wash5_notes = TextAreaField('Notes',validators=[Length(max=250)])
	wash1_ptwh_wash5_notes_submit = SubmitField('Update Notes')

	""" Secondary Antibody """
	antibody2_date = OptionalDateField('Secondary Antibody')
	antibody2_date_submit = SubmitField('Push date to calendar (optional)')
	time_antibody2_added = OptionalDateTimeLocalField('2nd antibody solution R@37°C for 7 days (3% donkey serum/PTwH)')
	time_antibody2_added_submit = SubmitField('Update')
	antibody2_added_notes = TextAreaField('Notes',validators=[Length(max=250)])
	antibody2_added_notes_submit = SubmitField('Update Notes')

	""" Wash 2 """
	wash2_date = OptionalDateField('Wash')
	wash2_date_submit = SubmitField('Push date to calendar (optional)')
	time_wash2_start_roomtemp = OptionalDateTimeLocalField('Sample R@RT for ~1.5hrs')
	time_wash2_start_roomtemp_submit = SubmitField('Update')
	wash2_start_roomtemp_notes = TextAreaField('Notes',validators=[Length(max=250)])
	wash2_start_roomtemp_notes_submit = SubmitField('Update Notes')
	time_wash2_ptwh_wash1 = OptionalDateTimeLocalField('PTwH 10 min')
	time_wash2_ptwh_wash1_submit = SubmitField('Update')
	wash2_ptwh_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	wash2_ptwh_wash1_notes_submit = SubmitField('Update Notes')
	time_wash2_ptwh_wash2 = OptionalDateTimeLocalField('PTwH 15 min')
	time_wash2_ptwh_wash2_submit = SubmitField('Update')
	wash2_ptwh_wash2_notes = TextAreaField('Notes',validators=[Length(max=250)])
	wash2_ptwh_wash2_notes_submit = SubmitField('Update Notes')
	time_wash2_ptwh_wash3 = OptionalDateTimeLocalField('PTwH 30 min')
	time_wash2_ptwh_wash3_submit = SubmitField('Update')
	wash2_ptwh_wash3_notes = TextAreaField('Notes',validators=[Length(max=250)])
	wash2_ptwh_wash3_notes_submit = SubmitField('Update Notes')
	time_wash2_ptwh_wash4 = OptionalDateTimeLocalField('PTwH 1 hr')
	time_wash2_ptwh_wash4_submit = SubmitField('Update')
	wash2_ptwh_wash4_notes = TextAreaField('Notes',validators=[Length(max=250)])
	wash2_ptwh_wash4_notes_submit = SubmitField('Update Notes')
	time_wash2_ptwh_wash5 = OptionalDateTimeLocalField('PTwH 2 hr')
	time_wash2_ptwh_wash5_submit = SubmitField('Update')
	wash2_ptwh_wash5_notes = TextAreaField('Notes',validators=[Length(max=250)])
	wash2_ptwh_wash5_notes_submit = SubmitField('Update Notes')

	""" Clearing """
	clearing_date = OptionalDateField('Clearing')
	clearing_date_submit = SubmitField('Push date to calendar (optional)')
	time_clearing_methanol_20percent_wash1 = OptionalDateTimeLocalField('20% methanol R@RTx1hr')
	time_clearing_methanol_20percent_wash1_submit = SubmitField('Update')
	clearing_methanol_20percent_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	clearing_methanol_20percent_wash1_notes_submit = SubmitField('Update Notes')
	time_clearing_methanol_40percent_wash1 = OptionalDateTimeLocalField('40% methanol R@RTx1hr')
	time_clearing_methanol_40percent_wash1_submit = SubmitField('Update')
	clearing_methanol_40percent_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	clearing_methanol_40percent_wash1_notes_submit = SubmitField('Update Notes')
	time_clearing_methanol_60percent_wash1 = OptionalDateTimeLocalField('60% methanol R@RTx1hr')
	time_clearing_methanol_60percent_wash1_submit = SubmitField('Update')
	clearing_methanol_60percent_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	clearing_methanol_60percent_wash1_notes_submit = SubmitField('Update Notes')
	time_clearing_methanol_80percent_wash1 = OptionalDateTimeLocalField('80% methanol R@RTx1hr')
	time_clearing_methanol_80percent_wash1_submit = SubmitField('Update')
	clearing_methanol_80percent_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	clearing_methanol_80percent_wash1_notes_submit = SubmitField('Update Notes')
	time_clearing_methanol_100percent_wash1 = OptionalDateTimeLocalField('100% methanol R@RTx1hr (hour 1)')
	time_clearing_methanol_100percent_wash1_submit = SubmitField('Update')
	clearing_methanol_100percent_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	clearing_methanol_100percent_wash1_notes_submit = SubmitField('Update Notes')
	time_clearing_methanol_100percent_wash2 = OptionalDateTimeLocalField('100% methanol R@RTx1hr (hour 2)')
	time_clearing_methanol_100percent_wash2_submit = SubmitField('Update')
	clearing_methanol_100percent_wash2_notes = TextAreaField('Notes',validators=[Length(max=250)])
	clearing_methanol_100percent_wash2_notes_submit = SubmitField('Update Notes')
	time_clearing_dcm_66percent_methanol_33percent = OptionalDateTimeLocalField('66% DCM / 33% methanol R@RTx3hrs')
	time_clearing_dcm_66percent_methanol_33percent_submit = SubmitField('Update')
	clearing_dcm_66percent_methanol_33percent_notes = TextAreaField('Notes',validators=[Length(max=250)])
	clearing_dcm_66percent_methanol_33percent_notes_submit = SubmitField('Update Notes')
	time_clearing_dcm_wash1 = OptionalDateTimeLocalField('100% DCM R@RTx15 min (wash 1)')
	time_clearing_dcm_wash1_submit = SubmitField('Update')
	clearing_dcm_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	clearing_dcm_wash1_notes_submit = SubmitField('Update Notes')
	time_clearing_dcm_wash2 = OptionalDateTimeLocalField('100% DCM R@RTx15 min (wash 2)')
	time_clearing_dcm_wash2_submit = SubmitField('Update')
	clearing_dcm_wash2_notes = TextAreaField('Notes',validators=[Length(max=250)])
	clearing_dcm_wash2_notes_submit = SubmitField('Update Notes')
	time_clearing_dbe = OptionalDateTimeLocalField('100% DBE > hr')
	time_clearing_dbe_submit = SubmitField('Update')
	clearing_dbe_notes = TextAreaField('Notes',validators=[Length(max=250)])
	clearing_dbe_notes_submit = SubmitField('Update Notes')
	time_clearing_new_tubes = OptionalDateTimeLocalField('put brains in new tubes with prepoured 100% DBE no rocking')
	time_clearing_new_tubes_submit = SubmitField('Update')
	clearing_new_tubes_notes = TextAreaField('Notes',validators=[Length(max=250)])
	clearing_new_tubes_notes_submit = SubmitField('Update Notes')
	clearing_notes = TextAreaField('Clearing Notes',validators=[Length(max=500)])
	clearing_notes_submit = SubmitField('Update')

	submit = SubmitField('Submit')

class iDiscoAbbreviatedForm(FlaskForm):
	""" The form for entering clearing information """
	title = 'iDISCO for non-oxidative fluorophores (abbreviated clearing)'
	exp_notes = TextAreaField('Experiment Notes: If anything unusual happened during \
		the experiment that might affect clearing, please note it here.',validators=[Length(max=500)])
	exp_notes_submit = SubmitField('Update')
	
	pbs_date = OptionalDateField('PBS wash')
	pbs_date_submit = SubmitField('Push date to calendar (optional)')
	time_pbs_wash1 = OptionalDateTimeLocalField('Wash 1')
	time_pbs_wash1_submit = SubmitField('Update')
	pbs_wash1_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	pbs_wash1_notes_submit = SubmitField('Update Notes')
	time_pbs_wash2 = OptionalDateTimeLocalField('Wash 2')
	time_pbs_wash2_submit = SubmitField('Update')
	pbs_wash2_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	pbs_wash2_notes_submit = SubmitField('Update Notes')
	time_pbs_wash3 = OptionalDateTimeLocalField('Wash 3')
	time_pbs_wash3_submit = SubmitField('Update')
	pbs_wash3_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	pbs_wash3_notes_submit = SubmitField('Update Notes')
	
	dehydr_date = OptionalDateField('Dehydration')
	dehydr_date_submit = SubmitField('Push date to calendar (optional)')
	time_dehydr_methanol_20percent_wash1 = OptionalDateTimeLocalField('20% methanol R@RTx1hr')
	time_dehydr_methanol_20percent_wash1_submit = SubmitField('Update')
	dehydr_methanol_20percent_wash1_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_methanol_20percent_wash1_notes_submit = SubmitField('Update Notes')
	time_dehydr_methanol_40percent_wash1 = OptionalDateTimeLocalField('40% methanol R@RTx1hr')
	time_dehydr_methanol_40percent_wash1_submit = SubmitField('Update')
	dehydr_methanol_40percent_wash1_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_methanol_40percent_wash1_notes_submit = SubmitField('Update Notes')
	time_dehydr_methanol_60percent_wash1 = OptionalDateTimeLocalField('60% methanol R@RTx1hr')
	time_dehydr_methanol_60percent_wash1_submit = SubmitField('Update')
	dehydr_methanol_60percent_wash1_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_methanol_60percent_wash1_notes_submit = SubmitField('Update Notes')
	time_dehydr_methanol_80percent_wash1 = OptionalDateTimeLocalField('80% methanol R@RTx1hr')
	time_dehydr_methanol_80percent_wash1_submit = SubmitField('Update')
	dehydr_methanol_80percent_wash1_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_methanol_80percent_wash1_notes_submit = SubmitField('Update Notes')
	time_dehydr_methanol_100percent_wash1 = OptionalDateTimeLocalField('100% methanol R@RTx1hr (first hour)')
	time_dehydr_methanol_100percent_wash1_submit = SubmitField('Update')
	dehydr_methanol_100percent_wash1_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_methanol_100percent_wash1_notes_submit = SubmitField('Update Notes')
	time_dehydr_methanol_100percent_wash2 = OptionalDateTimeLocalField('100% methanol R@RTx1hr (second hour)')
	time_dehydr_methanol_100percent_wash2_submit = SubmitField('Update')
	dehydr_methanol_100percent_wash2_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_methanol_100percent_wash2_notes_submit = SubmitField('Update Notes')
	time_dehydr_dcm_66percent_methanol_33percent = OptionalDateTimeLocalField('66% DCM / 33% methanol R@RTx3hrs')
	time_dehydr_dcm_66percent_methanol_33percent_submit = SubmitField('Update')
	dehydr_dcm_66percent_methanol_33percent_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_dcm_66percent_methanol_33percent_notes_submit = SubmitField('Update Notes')
	time_dehydr_dcm_wash1 = OptionalDateTimeLocalField('100% DCM R@RTx15 min (wash 1)')
	time_dehydr_dcm_wash1_submit = SubmitField('Update')
	dehydr_dcm_wash1_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_dcm_wash1_notes_submit = SubmitField('Update Notes')
	time_dehydr_dcm_wash2 = OptionalDateTimeLocalField('100% DCM R@RTx15 min (wash 2)')
	time_dehydr_dcm_wash2_submit = SubmitField('Update')
	dehydr_dcm_wash2_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_dcm_wash2_notes_submit = SubmitField('Update Notes')
	time_dehydr_dbe_wash1 = OptionalDateTimeLocalField('100% DBE > hr')
	time_dehydr_dbe_wash1_submit = SubmitField('Update')
	dehydr_dbe_wash1_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_dbe_wash1_notes_submit = SubmitField('Update Notes')
	time_dehydr_dbe_wash2 = OptionalDateTimeLocalField('100% DBE no rocking')
	time_dehydr_dbe_wash2_submit = SubmitField('Update')
	dehydr_dbe_wash2_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_dbe_wash2_notes_submit = SubmitField('Update Notes')
	clearing_notes = TextAreaField('Clearing Notes',validators=[Length(max=500)])
	clearing_notes_submit = SubmitField('Update')

	submit = SubmitField('Submit')

class iDiscoAbbreviatedRatForm(FlaskForm):
	""" The form for entering clearing information """
	title = 'Rat: iDISCO for non-oxidative fluorophores (abbreviated clearing)'
	exp_notes = TextAreaField('Experiment Notes: If anything unusual happened \
		during the experiment that might affect clearing, please note it here.',validators=[Length(max=500)])
	exp_notes_submit = SubmitField('Update')
	
	pbs_date = OptionalDateField('PBS wash')
	pbs_date_submit = SubmitField('Push date to calendar (optional)')
	time_pbs_wash1 = OptionalDateTimeLocalField('1xPBS R@RT30min')
	time_pbs_wash1_submit = SubmitField('Update')
	pbs_wash1_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	pbs_wash1_notes_submit = SubmitField('Update Notes')
	time_pbs_wash2 = OptionalDateTimeLocalField('1xPBS R@RT30min')
	time_pbs_wash2_submit = SubmitField('Update')
	pbs_wash2_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	pbs_wash2_notes_submit = SubmitField('Update Notes')
	time_pbs_wash3 = OptionalDateTimeLocalField('1xPBS R@RT30min')
	time_pbs_wash3_submit = SubmitField('Update')
	pbs_wash3_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	pbs_wash3_notes_submit = SubmitField('Update Notes')
	
	dehydr_date = OptionalDateField('Dehydration')
	dehydr_date_submit = SubmitField('Push date to calendar (optional)')
	
	time_dehydr_methanol_20percent_wash1 = OptionalDateTimeLocalField('20% methanol R@RTX3hrs (wash 1/2)')
	time_dehydr_methanol_20percent_wash1_submit = SubmitField('Update')
	dehydr_methanol_20percent_wash1_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_methanol_20percent_wash1_notes_submit = SubmitField('Update Notes')
	time_dehydr_methanol_20percent_wash2 = OptionalDateTimeLocalField('20% methanol R@RTX3hrs (wash 2/2)')
	time_dehydr_methanol_20percent_wash2_submit = SubmitField('Update')
	dehydr_methanol_20percent_wash2_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_methanol_20percent_wash2_notes_submit = SubmitField('Update Notes')

	time_dehydr_methanol_40percent_wash1 = OptionalDateTimeLocalField('40% methanol R@RTX3hrs (wash 1/2)')
	time_dehydr_methanol_40percent_wash1_submit = SubmitField('Update')
	dehydr_methanol_40percent_wash1_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_methanol_40percent_wash1_notes_submit = SubmitField('Update Notes')
	time_dehydr_methanol_40percent_wash2 = OptionalDateTimeLocalField('40% methanol R@RTX3hrs (wash 2/2)')
	time_dehydr_methanol_40percent_wash2_submit = SubmitField('Update')
	dehydr_methanol_40percent_wash2_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_methanol_40percent_wash2_notes_submit = SubmitField('Update Notes')

	time_dehydr_methanol_60percent_wash1 = OptionalDateTimeLocalField('60% methanol R@RTX3hrs')
	time_dehydr_methanol_60percent_wash1_submit = SubmitField('Update')
	dehydr_methanol_60percent_wash1_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_methanol_60percent_wash1_notes_submit = SubmitField('Update Notes')
	
	time_dehydr_methanol_80percent_wash1 = OptionalDateTimeLocalField('80% methanol R@RTX3hrs (wash 1/2)')
	time_dehydr_methanol_80percent_wash1_submit = SubmitField('Update')
	dehydr_methanol_80percent_wash1_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_methanol_80percent_wash1_notes_submit = SubmitField('Update Notes')
	time_dehydr_methanol_80percent_wash2 = OptionalDateTimeLocalField('80% methanol R@RTX3hrs (wash 2/2)')
	time_dehydr_methanol_80percent_wash2_submit = SubmitField('Update')
	dehydr_methanol_80percent_wash2_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_methanol_80percent_wash2_notes_submit = SubmitField('Update Notes')
	
	time_dehydr_methanol_100percent_wash1 = OptionalDateTimeLocalField('100% methanol R@RTX3hrs')
	time_dehydr_methanol_100percent_wash1_submit = SubmitField('Update')
	dehydr_methanol_100percent_wash1_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_methanol_100percent_wash1_notes_submit = SubmitField('Update Notes')
	time_dehydr_methanol_100percent_wash2 = OptionalDateTimeLocalField('100% methanol R@RTX3hrs (or overnight)')
	time_dehydr_methanol_100percent_wash2_submit = SubmitField('Update')
	dehydr_methanol_100percent_wash2_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_methanol_100percent_wash2_notes_submit = SubmitField('Update Notes')
	time_dehydr_peroxide_wash1 = OptionalDateTimeLocalField('5% peroxide / Methanol (1 part 30% peroxide: 5 parts 100% methanol) ')
	time_dehydr_peroxide_wash1_submit = SubmitField('Update')
	dehydr_peroxide_wash1_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_peroxide_wash1_notes_submit = SubmitField('Update Notes')
	time_dehydr_methanol_100percent_wash3 = OptionalDateTimeLocalField('100% methanol R@RTX2hrs')
	time_dehydr_methanol_100percent_wash3_submit = SubmitField('Update')
	dehydr_methanol_100percent_wash3_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_methanol_100percent_wash3_notes_submit = SubmitField('Update Notes')
	time_dehydr_methanol_100percent_wash4 = OptionalDateTimeLocalField('100% methanol R@RTX2hrs')
	time_dehydr_methanol_100percent_wash4_submit = SubmitField('Update')
	dehydr_methanol_100percent_wash4_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_methanol_100percent_wash4_notes_submit = SubmitField('Update Notes')
	time_dehydr_methanol_100percent_wash5 = OptionalDateTimeLocalField('100% methanol R@RTX2hrs (or overnight)')
	time_dehydr_methanol_100percent_wash5_submit = SubmitField('Update')
	dehydr_methanol_100percent_wash5_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_methanol_100percent_wash5_notes_submit = SubmitField('Update Notes')

	time_dehydr_dcm_66percent_methanol_33percent = OptionalDateTimeLocalField('66% DCM / 33% methanol R@RTx6hrs')
	time_dehydr_dcm_66percent_methanol_33percent_submit = SubmitField('Update')
	dehydr_dcm_66percent_methanol_33percent_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_dcm_66percent_methanol_33percent_notes_submit = SubmitField('Update Notes')
	time_dehydr_dcm_wash1 = OptionalDateTimeLocalField('100% DCM R@RTx1hr (wash 1)')
	time_dehydr_dcm_wash1_submit = SubmitField('Update')
	dehydr_dcm_wash1_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_dcm_wash1_notes_submit = SubmitField('Update Notes')
	time_dehydr_dcm_wash2 = OptionalDateTimeLocalField('100% DCM R@RTx1hr (wash 2)')
	time_dehydr_dcm_wash2_submit = SubmitField('Update')
	dehydr_dcm_wash2_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_dcm_wash2_notes_submit = SubmitField('Update Notes')
	time_dehydr_dbe_wash1 = OptionalDateTimeLocalField('100% DBE > 3 hrs')
	time_dehydr_dbe_wash1_submit = SubmitField('Update')
	dehydr_dbe_wash1_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_dbe_wash1_notes_submit = SubmitField('Update Notes')
	time_dehydr_dbe_wash2 = OptionalDateTimeLocalField('100% DBE no rocking')
	time_dehydr_dbe_wash2_submit = SubmitField('Update')
	dehydr_dbe_wash2_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_dbe_wash2_notes_submit = SubmitField('Update Notes')

	clearing_notes = TextAreaField('Clearing Notes',validators=[Length(max=500)])
	clearing_notes_submit = SubmitField('Update')

	submit = SubmitField('Submit')

class uDiscoForm(FlaskForm):
	""" The form for requesting a new experiment/dataset """
	title = 'uDISCO'
	exp_notes = TextAreaField('Experiment Notes: If anything unusual happened \
		during the experiment that might affect clearing, please note it here:',validators=[Length(max=500)])
	exp_notes_submit = SubmitField('Update')
	
	dehydr_date = OptionalDateField('Dehydration')
	dehydr_date_submit = SubmitField('Push date to calendar (optional)')
	time_dehydr_pbs_wash1 = OptionalDateTimeLocalField('0.1M PBS R@RT5min')
	time_dehydr_pbs_wash1_submit = SubmitField('Update')
	dehydr_pbs_wash1_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_pbs_wash1_notes_submit = SubmitField('Update Notes')

	time_dehydr_butanol_30percent = OptionalDateTimeLocalField('30% t-butanol R@35C O/N')
	time_dehydr_butanol_30percent_submit = SubmitField('Update')
	dehydr_butanol_30percent_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_butanol_30percent_notes_submit = SubmitField('Update Notes')

	time_dehydr_butanol_50percent = OptionalDateTimeLocalField('50% t-butanol R@35C 10 h')
	time_dehydr_butanol_50percent_submit = SubmitField('Update')
	dehydr_butanol_50percent_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_butanol_50percent_notes_submit = SubmitField('Update Notes')

	time_dehydr_butanol_70percent = OptionalDateTimeLocalField('70% t-butanol R@35C O/N')
	time_dehydr_butanol_70percent_submit = SubmitField('Update')
	dehydr_butanol_70percent_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_butanol_70percent_notes_submit = SubmitField('Update Notes')

	time_dehydr_butanol_80percent = OptionalDateTimeLocalField('80% t-butanol R@35C 10 h')
	time_dehydr_butanol_80percent_submit = SubmitField('Update')
	dehydr_butanol_80percent_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_butanol_80percent_notes_submit = SubmitField('Update Notes')

	time_dehydr_butanol_90percent = OptionalDateTimeLocalField('90% t-butanol R@35C O/N')
	time_dehydr_butanol_90percent_submit = SubmitField('Update')
	dehydr_butanol_90percent_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_butanol_90percent_notes_submit = SubmitField('Update Notes')

	time_dehydr_butanol_96percent = OptionalDateTimeLocalField('96% t-butanol R@35C 10 h')
	time_dehydr_butanol_96percent_submit = SubmitField('Update')
	dehydr_butanol_96percent_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_butanol_96percent_notes_submit = SubmitField('Update Notes')

	time_dehydr_butanol_100percent = OptionalDateTimeLocalField('100% t-butanol R@35C O/N')
	time_dehydr_butanol_100percent_submit = SubmitField('Update')
	dehydr_butanol_100percent_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	dehydr_butanol_100percent_notes_submit = SubmitField('Update Notes')

	
	clearing_date = OptionalDateField('Clearing')
	clearing_date_submit = SubmitField('Push date to calendar (optional)')
	time_clearing_dcm_wash1 = OptionalDateTimeLocalField('100% DCM R@RT 50-70min')
	time_clearing_dcm_wash1_submit = SubmitField('Update')
	clearing_dcm_wash1_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	clearing_dcm_wash1_notes_submit = SubmitField('Update Notes')

	time_clearing_babb_wash1 = OptionalDateTimeLocalField('BABB-D10 >3hrs')
	time_clearing_babb_wash1_submit = SubmitField('Update')
	clearing_babb_wash1_notes = TextAreaField('Notes:',validators=[Length(max=250)])
	clearing_babb_wash1_notes_submit = SubmitField('Update Notes')

	clearing_notes = TextAreaField('Clearing Notes',validators=[Length(max=500)])
	clearing_notes_submit = SubmitField('Update Notes')

	submit = SubmitField('Submit')

class iDiscoEduForm(FlaskForm):
	""" The form for entering clearing information """
	title = 'iDISCO+ Immunostaining'
	exp_notes = TextAreaField('Experiment Notes: If anything unusual happened during the \
		experiment that might affect clearing, please note it here.',validators=[Length(max=500)])
	exp_notes_submit = SubmitField('Update')

	dehydr_date = OptionalDateField('Dehydration')
	dehydr_date_submit = SubmitField('Push date to calendar (optional)')
	time_dehydr_pbs_wash1 = OptionalDateTimeLocalField('1xPBS 30 min R@RT')
	time_dehydr_pbs_wash1_submit = SubmitField('Update')
	dehydr_pbs_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	dehydr_pbs_wash1_notes_submit = SubmitField('Update Notes')
	time_dehydr_pbs_wash2 = OptionalDateTimeLocalField('2xPBS 30 min R@RT')
	time_dehydr_pbs_wash2_submit = SubmitField('Update')
	dehydr_pbs_wash2_notes = TextAreaField('Notes',validators=[Length(max=250)])
	dehydr_pbs_wash2_notes_submit = SubmitField('Update Notes')
	time_dehydr_pbs_wash3 = OptionalDateTimeLocalField('3xPBS 30 min R@RT')
	time_dehydr_pbs_wash3_submit = SubmitField('Update')
	dehydr_pbs_wash3_notes = TextAreaField('Notes',validators=[Length(max=250)])
	dehydr_pbs_wash3_notes_submit = SubmitField('Update Notes')
	time_dehydr_methanol_20percent_wash1 = OptionalDateTimeLocalField('20% methanol R@RTx1hr')
	time_dehydr_methanol_20percent_wash1_submit = SubmitField('Update')
	dehydr_methanol_20percent_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	dehydr_methanol_20percent_wash1_notes_submit = SubmitField('Update Notes')
	time_dehydr_methanol_40percent_wash1 = OptionalDateTimeLocalField('40% methanol R@RTx1hr')
	time_dehydr_methanol_40percent_wash1_submit = SubmitField('Update')
	dehydr_methanol_40percent_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	dehydr_methanol_40percent_wash1_notes_submit = SubmitField('Update Notes')
	time_dehydr_methanol_60percent_wash1 = OptionalDateTimeLocalField('60% methanol R@RTx1hr')
	time_dehydr_methanol_60percent_wash1_submit = SubmitField('Update')
	dehydr_methanol_60percent_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	dehydr_methanol_60percent_wash1_notes_submit = SubmitField('Update Notes')
	time_dehydr_methanol_80percent_wash1 = OptionalDateTimeLocalField('80% methanol R@RTx1hr')
	time_dehydr_methanol_80percent_wash1_submit = SubmitField('Update')
	dehydr_methanol_80percent_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	dehydr_methanol_80percent_wash1_notes_submit = SubmitField('Update Notes')

	time_dehydr_methanol_100percent_wash1 = OptionalDateTimeLocalField('100% methanol R@RTx1hr (first hour)')
	time_dehydr_methanol_100percent_wash1_submit = SubmitField('Update')
	dehydr_methanol_100percent_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	dehydr_methanol_100percent_wash1_notes_submit = SubmitField('Update Notes')

	time_dehydr_methanol_100percent_wash2 = OptionalDateTimeLocalField('100% methanol R@RTx1hr (second hour)')
	time_dehydr_methanol_100percent_wash2_submit = SubmitField('Update')
	dehydr_methanol_100percent_wash2_notes = TextAreaField('Notes',validators=[Length(max=250)])
	dehydr_methanol_100percent_wash2_notes_submit = SubmitField('Update Notes')
	time_dehydr_peroxide_wash1 = OptionalDateTimeLocalField('5% H2O2 (30%) in methanol(100%) O/N R@RT (1 part H2O2:5 parts methanol)')
	time_dehydr_peroxide_wash1_submit = SubmitField('Update')
	dehydr_peroxide_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	dehydr_peroxide_wash1_notes_submit = SubmitField('Update Notes')

	rehydr_date = OptionalDateField('Rehydration')
	rehydr_date_submit = SubmitField('Push date to calendar (optional)')
	time_rehydr_methanol_100percent_wash1 = OptionalDateTimeLocalField('100% methanol R@RTx1hr')
	time_rehydr_methanol_100percent_wash1_submit = SubmitField('Update')
	rehydr_methanol_100percent_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	rehydr_methanol_100percent_wash1_notes_submit = SubmitField('Update Notes')
	time_rehydr_methanol_80percent_wash1 = OptionalDateTimeLocalField('80% methanol R@RTx1hr')
	time_rehydr_methanol_80percent_wash1_submit = SubmitField('Update')
	rehydr_methanol_80percent_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	rehydr_methanol_80percent_wash1_notes_submit = SubmitField('Update Notes')
	time_rehydr_methanol_60percent_wash1 = OptionalDateTimeLocalField('60% methanol R@RTx1hr')
	time_rehydr_methanol_60percent_wash1_submit = SubmitField('Update')
	rehydr_methanol_60percent_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	rehydr_methanol_60percent_wash1_notes_submit = SubmitField('Update Notes')
	time_rehydr_methanol_40percent_wash1 = OptionalDateTimeLocalField('40% methanol R@RTx1hr')
	time_rehydr_methanol_40percent_wash1_submit = SubmitField('Update')
	rehydr_methanol_40percent_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	rehydr_methanol_40percent_wash1_notes_submit = SubmitField('Update Notes')
	time_rehydr_methanol_20percent_wash1 = OptionalDateTimeLocalField('20% methanol R@RTx1hr')
	time_rehydr_methanol_20percent_wash1_submit = SubmitField('Update')
	rehydr_methanol_20percent_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	rehydr_methanol_20percent_wash1_notes_submit = SubmitField('Update Notes')
	time_rehydr_pbs_wash1 = OptionalDateTimeLocalField('PBS R@RTx1hr')
	time_rehydr_pbs_wash1_submit = SubmitField('Update')
	rehydr_pbs_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	rehydr_pbs_wash1_notes_submit = SubmitField('Update Notes')
	time_rehydr_sodium_azide_wash1 = OptionalDateTimeLocalField('0.2%TritonX-100/1xPBS/0.1% sodium azide R@RTx1hr (first hour)')
	time_rehydr_sodium_azide_wash1_submit = SubmitField('Update')
	rehydr_sodium_azide_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	rehydr_sodium_azide_wash1_notes_submit = SubmitField('Update Notes')
	time_rehydr_sodium_azide_wash2 = OptionalDateTimeLocalField('0.2%TritonX-100/1xPBS/0.1% sodium azide R@RTx1hr (second hour)')
	time_rehydr_sodium_azide_wash2_submit = SubmitField('Update')
	rehydr_sodium_azide_wash2_notes = TextAreaField('Notes',validators=[Length(max=250)])
	rehydr_sodium_azide_wash2_notes_submit = SubmitField('Update Notes')
	time_rehydr_glycine_wash1 = OptionalDateTimeLocalField('20%DMSO/0.3M glycine/0.2% TritonX-100/0.1%sodium azide/1xPBS R@37C for 2 days')
	time_rehydr_glycine_wash1_submit = SubmitField('Update')
	rehydr_glycine_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	rehydr_glycine_wash1_notes_submit = SubmitField('Update Notes')

	wash1_date = OptionalDateField('Wash')
	wash1_date_submit = SubmitField('Push date to calendar (optional)')
	time_wash1_start_roomtemp = OptionalDateTimeLocalField('Sample R@RT for ~1.5hrs')
	time_wash1_start_roomtemp_submit = SubmitField('Update')
	wash1_start_roomtemp_notes = TextAreaField('Notes',validators=[Length(max=250)])
	wash1_start_roomtemp_notes_submit = SubmitField('Update Notes')
	time_wash1_ptwh_wash1 = OptionalDateTimeLocalField('PTwH 10 min')
	time_wash1_ptwh_wash1_submit = SubmitField('Update')
	wash1_ptwh_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	wash1_ptwh_wash1_notes_submit = SubmitField('Update Notes')
	time_wash1_ptwh_wash2 = OptionalDateTimeLocalField('PTwH 15 min')
	time_wash1_ptwh_wash2_submit = SubmitField('Update')
	wash1_ptwh_wash2_notes = TextAreaField('Notes',validators=[Length(max=250)])
	wash1_ptwh_wash2_notes_submit = SubmitField('Update Notes')
	time_wash1_ptwh_wash3 = OptionalDateTimeLocalField('PTwH 30 min')
	time_wash1_ptwh_wash3_submit = SubmitField('Update')
	wash1_ptwh_wash3_notes = TextAreaField('Notes',validators=[Length(max=250)])
	wash1_ptwh_wash3_notes_submit = SubmitField('Update Notes')
	time_wash1_ptwh_wash4 = OptionalDateTimeLocalField('PTwH 1 hr')
	time_wash1_ptwh_wash4_submit = SubmitField('Update')
	wash1_ptwh_wash4_notes = TextAreaField('Notes',validators=[Length(max=250)])
	wash1_ptwh_wash4_notes_submit = SubmitField('Update Notes')
	time_wash1_ptwh_wash5 = OptionalDateTimeLocalField('PTwH 2 hr')
	time_wash1_ptwh_wash5_submit = SubmitField('Update')
	wash1_ptwh_wash5_notes = TextAreaField('Notes',validators=[Length(max=250)])
	wash1_ptwh_wash5_notes_submit = SubmitField('Update Notes')

	edu_click_chemistry_date = OptionalDateField('EdU click chemistry')
	edu_click_chemistry_date_submit = SubmitField('Push date to calendar (optional)')
	
	wash2_date = OptionalDateField('Wash')
	wash2_date_submit = SubmitField('Push date to calendar (optional)')
	
	wash2_start_roomtemp_notes = TextAreaField('Notes',validators=[Length(max=250)])
	wash2_start_roomtemp_notes_submit = SubmitField('Update Notes')
	time_wash2_ptwh_wash1 = OptionalDateTimeLocalField('PTwH 10 min')
	time_wash2_ptwh_wash1_submit = SubmitField('Update')
	wash2_ptwh_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	wash2_ptwh_wash1_notes_submit = SubmitField('Update Notes')
	time_wash2_ptwh_wash2 = OptionalDateTimeLocalField('PTwH 15 min')
	time_wash2_ptwh_wash2_submit = SubmitField('Update')
	wash2_ptwh_wash2_notes = TextAreaField('Notes',validators=[Length(max=250)])
	wash2_ptwh_wash2_notes_submit = SubmitField('Update Notes')
	time_wash2_ptwh_wash3 = OptionalDateTimeLocalField('PTwH 30 min')
	time_wash2_ptwh_wash3_submit = SubmitField('Update')
	wash2_ptwh_wash3_notes = TextAreaField('Notes',validators=[Length(max=250)])
	wash2_ptwh_wash3_notes_submit = SubmitField('Update Notes')
	time_wash2_ptwh_wash4 = OptionalDateTimeLocalField('PTwH 1 hr')
	time_wash2_ptwh_wash4_submit = SubmitField('Update')
	wash2_ptwh_wash4_notes = TextAreaField('Notes',validators=[Length(max=250)])
	wash2_ptwh_wash4_notes_submit = SubmitField('Update Notes')
	time_wash2_ptwh_wash5 = OptionalDateTimeLocalField('PTwH 2 hr')
	time_wash2_ptwh_wash5_submit = SubmitField('Update')
	wash2_ptwh_wash5_notes = TextAreaField('Notes',validators=[Length(max=250)])
	wash2_ptwh_wash5_notes_submit = SubmitField('Update Notes')

	clearing_date = OptionalDateField('Clearing')
	clearing_date_submit = SubmitField('Push date to calendar (optional)')
	time_clearing_methanol_20percent_wash1 = OptionalDateTimeLocalField('20% methanol R@RTx1hr')
	time_clearing_methanol_20percent_wash1_submit = SubmitField('Update')
	clearing_methanol_20percent_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	clearing_methanol_20percent_wash1_notes_submit = SubmitField('Update Notes')
	time_clearing_methanol_40percent_wash1 = OptionalDateTimeLocalField('40% methanol R@RTx1hr')
	time_clearing_methanol_40percent_wash1_submit = SubmitField('Update')
	clearing_methanol_40percent_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	clearing_methanol_40percent_wash1_notes_submit = SubmitField('Update Notes')
	time_clearing_methanol_60percent_wash1 = OptionalDateTimeLocalField('60% methanol R@RTx1hr')
	time_clearing_methanol_60percent_wash1_submit = SubmitField('Update')
	clearing_methanol_60percent_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	clearing_methanol_60percent_wash1_notes_submit = SubmitField('Update Notes')
	time_clearing_methanol_80percent_wash1 = OptionalDateTimeLocalField('80% methanol R@RTx1hr')
	time_clearing_methanol_80percent_wash1_submit = SubmitField('Update')
	clearing_methanol_80percent_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	clearing_methanol_80percent_wash1_notes_submit = SubmitField('Update Notes')
	time_clearing_methanol_100percent_wash1 = OptionalDateTimeLocalField('100% methanol R@RTx1hr (hour 1)')
	time_clearing_methanol_100percent_wash1_submit = SubmitField('Update')
	clearing_methanol_100percent_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	clearing_methanol_100percent_wash1_notes_submit = SubmitField('Update Notes')
	time_clearing_methanol_100percent_wash2 = OptionalDateTimeLocalField('100% methanol R@RTx1hr (hour 2)')
	time_clearing_methanol_100percent_wash2_submit = SubmitField('Update')
	clearing_methanol_100percent_wash2_notes = TextAreaField('Notes',validators=[Length(max=250)])
	clearing_methanol_100percent_wash2_notes_submit = SubmitField('Update Notes')
	time_clearing_dcm_66percent_methanol_33percent = OptionalDateTimeLocalField('66% DCM / 33% methanol R@RTx3hrs')
	time_clearing_dcm_66percent_methanol_33percent_submit = SubmitField('Update')
	clearing_dcm_66percent_methanol_33percent_notes = TextAreaField('Notes',validators=[Length(max=250)])
	clearing_dcm_66percent_methanol_33percent_notes_submit = SubmitField('Update Notes')
	time_clearing_dcm_wash1 = OptionalDateTimeLocalField('100% DCM R@RTx15 min (wash 1)')
	time_clearing_dcm_wash1_submit = SubmitField('Update')
	clearing_dcm_wash1_notes = TextAreaField('Notes',validators=[Length(max=250)])
	clearing_dcm_wash1_notes_submit = SubmitField('Update Notes')
	time_clearing_dcm_wash2 = OptionalDateTimeLocalField('100% DCM R@RTx15 min (wash 2)')
	time_clearing_dcm_wash2_submit = SubmitField('Update')
	clearing_dcm_wash2_notes = TextAreaField('Notes',validators=[Length(max=250)])
	clearing_dcm_wash2_notes_submit = SubmitField('Update Notes')
	time_clearing_dbe = OptionalDateTimeLocalField('100% DBE > hr')
	time_clearing_dbe_submit = SubmitField('Update')
	clearing_dbe_notes = TextAreaField('Notes',validators=[Length(max=250)])
	clearing_dbe_notes_submit = SubmitField('Update Notes')
	time_clearing_new_tubes = OptionalDateTimeLocalField('put brains in new tubes with prepoured 100% DBE no rocking')
	time_clearing_new_tubes_submit = SubmitField('Update')
	clearing_new_tubes_notes = TextAreaField('Notes',validators=[Length(max=250)])
	clearing_new_tubes_notes_submit = SubmitField('Update Notes')
	clearing_notes = TextAreaField('Clearing Notes',validators=[Length(max=500)])
	clearing_notes_submit = SubmitField('Update')

	submit = SubmitField('Submit')